<a href="https://colab.research.google.com/github/CatMolnia/Studies/blob/main/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B8/Pandas%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8/%D0%93%D0%BB%D0%B0%D0%B2%D0%B0%202%20%D0%9E%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%20Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""---2. ОБОЪЕКТ SERIES---"""

"""---2.1 ОБЗОР SERIES---"""

"""---2.1.3. Пользовательские индексы для Series---"""

In [1]:
import pandas as pd
import numpy as np

In [2]:
ice_cream_flavors = [
  "Chocolate",
  "Vanilla",
  "Strawberry",
  "Rum Raisin",
]

pd.Series(ice_cream_flavors) # создание объекта Series

0     Chocolate
1       Vanilla
2    Strawberry
3    Rum Raisin
dtype: object

In [3]:
days_of_week = ("Monday", "Wednesday", "Friday", "Saturday")

In [4]:
pd.Series(ice_cream_flavors, days_of_week)
pd.Series(data = ice_cream_flavors, index = days_of_week)

Monday        Chocolate
Wednesday       Vanilla
Friday       Strawberry
Saturday     Rum Raisin
dtype: object

In [5]:
bunch_of_bools = [True, False, False]
pd.Series(bunch_of_bools)

0     True
1    False
2    False
dtype: bool

In [6]:
stock_prices = [985.32, 950.44]
time_of_day = ["Open", "Close"]
pd.Series(data = stock_prices, index = time_of_day)

Open     985.32
Close    950.44
dtype: float64

In [7]:
lucky_numbers = [4, 8, 15, 16, 23, 42]
pd.Series(lucky_numbers)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In [8]:
lucky_numbers = [4, 8, 15, 16, 23, 42]
pd.Series(lucky_numbers, dtype = "float") # принудительно меняем формат передаваемых данных

0     4.0
1     8.0
2    15.0
3    16.0
4    23.0
5    42.0
dtype: float64

"""---2.1.4. Создание объекта Series
с пропущенными значениями---""

In [9]:
temperatures = [94, 88, np.nan, 91] # создаем пропущенное значение в объекте Series
pd.Series(temperatures)

0    94.0
1    88.0
2     NaN
3    91.0
dtype: float64

"""---2.2 СОЗДАНИЕ ОБЪЕКТОВ SERIES НА ОСНОВЕ ОБЪЕКТА ЯЗЫКА PYTHON---"""

In [10]:
# ассоциативный массив (словарь) (ключ: значение)
calorie_info = {
  "Cereal": 125,
  "Chocolate Bar": 406,
  "Ice Cream Sundae": 342,
}

diet = pd.Series(calorie_info)

diet

Cereal              125
Chocolate Bar       406
Ice Cream Sundae    342
dtype: int64

In [11]:
# кортежи
pd.Series(data = ("Red", "Green", "Blue")) # кортеж (неизменяемый список)

0      Red
1    Green
2     Blue
dtype: object

In [12]:
# кортежи в списке
rgb_colors = [(120, 41, 26), (196, 165, 45)] # кортежи, заключенные в список
pd.Series(data = rgb_colors)

0     (120, 41, 26)
1    (196, 165, 45)
dtype: object

In [13]:
# множество
my_set = {"Ricky", "Bobby"}
pd.Series(list(my_set)) # преобразуем множество в список (иначе будет ошибка)

0    Ricky
1    Bobby
dtype: object

In [14]:
# объект ndarray библиотеки NymPy
random_data = np.random.randint(1, 101, 10)
random_data

array([56,  9, 66, 95, 84, 80, 61, 94,  2, 21])

In [15]:
pd.Series(random_data) # передаем в Series объект ndarray

0    56
1     9
2    66
3    95
4    84
5    80
6    61
7    94
8     2
9    21
dtype: int64

"""---2.3 АТРИБУТЫ SERIES---"""

In [16]:
diet = {
    'Cereal': 125,
    'Chocolate Bar': 406,
    'Ice Cream Sundae': 342,
}

In [17]:
np.array(diet.values()) # обращаемся к объекту ndarray, в котором храняться значения

array(dict_values([125, 406, 342]), dtype=object)

In [18]:
pd.Series(diet).index # обращаемся к Series для определения индекса

Index(['Cereal', 'Chocolate Bar', 'Ice Cream Sundae'], dtype='object')

In [19]:
pd.Series(diet).dtype # обращаемся к Series для определения типа данных

dtype('int64')

In [20]:
pd.Series(diet).size # обращаемся к Series для определения количества элементов

3

In [21]:
pd.Series(diet).shape # обращаемся к Series для определения формы данных

(3,)

In [22]:
pd.Series(diet).is_unique # обращаемся к Series для определения уникальности данных

True

In [23]:
pd.Series(data=[3, 2, 1]).is_monotonic_decreasing # обращаемся к Series для определения монотонности данных (убывание)

True

In [24]:
pd.Series(data=[1, 3, 2]).is_monotonic_increasing # обращаемся к Series для определения монотонности данных (возрастание)

False

"""---2.4 ВОЗВРЩЕНИЕ ПЕРВОЙ И ПОСЛЕДНЕЙ СТРОК---"""

In [44]:
values = range(0, 500, 5)
pd.Series(data=values)

0       0
1       5
2      10
3      15
4      20
     ...
95    475
96    480
97    485
98    490
99    495
Length: 100, dtype: int64

In [45]:
nums.head(3) # возвращаем первые 3 строки

0     0
1     5
2    10
dtype: int64

In [46]:
nums.tail(3) # возвращаем последние 3 строки

97    485
98    490
99    495
dtype: int64

"""---2.5 МАТЕМАТИЧЕСКИЕ ОПЕРАЦИИ---"""

"""---2.5.1. Статистические операции---"""

In [34]:
numbers = pd.Series([1, 2, 3, np.nan, 4, 5])
numbers

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [35]:
numbers.count() # подсчет непустых значений

np.int64(5)

In [36]:
numbers.sum() # сумма непустых значений

np.float64(15.0)

In [37]:
numbers.sum(skipna = False) # определение суммы значений с пропущенными значениями

np.float64(nan)

In [38]:
numbers.sum(min_count = 3) # определение суммы значений с минимальным количеством непустых значений

np.float64(15.0)